import {describe,it,expect} from 'vitest';
import {Game} from '../src/core/game';
import {blankWorld,placeBlueprint} from '../src/world/generate';
import {computerComplex,logicVault} from '../src/world/puzzles';
import {updateCircuits} from '../src/systems/circuits';
import {stack} from '../src/core/inventory';
import {HOUSES,CITY} from '../src/world/blueprints';
function fixture(which:'city_2'|'city_7'){const w=blankWorld();placeBlueprint(w,which==='city_2'?computerComplex():logicVault(),40,30,true);const g=new Game(w);return {g,tag:(name:string)=>w.entities.find(e=>e.tag===`${which}-${name}`)!};}
function settle(g:Game,seconds=2){for(let i=0;i<seconds*10;i++)updateCircuits(g,.1);}
describe('authored city wiring',()=>{
 it('opens the small city safe room with its switch or a weighted platform',()=>{const w=blankWorld();placeBlueprint(w,CITY[4],40,30,true);const g=new Game(w),button=w.entities.find(e=>e.type==='switch')!,plate=w.entities.find(e=>e.type==='platform')!,door=w.entities.find(e=>e.type==='automatic_door')!;button.switchOn=false;settle(g);expect(door.open).toBe(false);button.switchOn=true;settle(g);expect(door.open).toBe(true);button.switchOn=false;settle(g);expect(door.open).toBe(false);g.drop(stack(w,'stone'),plate);settle(g);expect(door.open).toBe(true);});
 it('requires all three garden switches for the protected-house store',()=>{for(let bits=0;bits<8;bits++){const w=blankWorld();placeBlueprint(w,HOUSES[8],40,30);const g=new Game(w);for(let i=1;i<=3;i++)w.entities.find(e=>e.tag===`house_9-store-switch-${i}`)!.switchOn=!!(bits&(1<<(i-1)));settle(g);expect(w.entities.find(e=>e.tag==='house_9-store-door')!.open,`switches ${bits}`).toBe(bits===7);}});
 it('requires both entrance platforms and does not shade the outdoor garden',()=>{const w=blankWorld();placeBlueprint(w,HOUSES[8],40,30);const g=new Game(w),plates=w.entities.filter(e=>e.tag?.startsWith('house_9-entry-platform')),door=w.entities.find(e=>e.tag==='house_9-entry-door')!;settle(g);expect(door.open).toBe(false);g.drop(stack(w,'stone'),plates[0]);settle(g);expect(door.open).toBe(false);g.drop(stack(w,'stone'),plates[1]);settle(g);expect(door.open).toBe(true);expect(g.inShelter({x:(40+2)*64+32,y:(30+2)*64+32})).toBe(false);expect(g.inShelter({x:(40+12)*64+32,y:(30+8)*64+32})).toBe(true);});
 it('connects the cafe switch through its wall to both automatic doors',()=>{const w=blankWorld();placeBlueprint(w,HOUSES[7],40,30);const g=new Game(w),button=w.entities.find(e=>e.type==='switch')!,doors=w.entities.filter(e=>e.type==='automatic_door');settle(g);expect(doors.every(e=>!e.open)).toBe(true);button.switchOn=true;settle(g);expect(doors).toHaveLength(2);expect(doors.every(e=>e.open)).toBe(true);button.switchOn=false;settle(g);expect(doors.every(e=>!e.open)).toBe(true);});
 it('operates the office entrance from its outside platform or interior switch',()=>{const w=blankWorld();placeBlueprint(w,HOUSES[5],40,30);const g=new Game(w),plate=w.entities.find(e=>e.type==='platform')!,button=w.entities.find(e=>e.type==='switch')!,doors=w.entities.filter(e=>e.type==='automatic_door');settle(g);expect(doors.every(e=>!e.open)).toBe(true);const drop=g.drop(stack(w,'stone'),plate);settle(g);expect(doors.every(e=>e.open)).toBe(true);drop.active=false;g.spatial.remove(drop);settle(g);expect(doors.every(e=>!e.open)).toBe(true);button.switchOn=true;settle(g);expect(doors.every(e=>e.open)).toBe(true);});
 it('opens the computer room for only red-green-green-red-green-green',()=>{for(let bits=0;bits<64;bits++){const {g,tag}=fixture('city_2');for(let i=0;i<6;i++)tag(`switch-${i+1}`).switchOn=!!(bits&(1<<i));settle(g);expect(tag('computer-door').open,`combination ${bits}`).toBe(bits===54);}});
 it('lets a dropped spear weight the alternative entry and closes when collected',()=>{const {g,tag}=fixture('city_2');const plate=tag('spear-platform');const drop=g.drop(stack(g.world,'spear'),plate);settle(g);expect(tag('computer-door').open).toBe(true);drop.active=false;g.spatial.remove(drop);settle(g);expect(tag('computer-door').open).toBe(false);});
 it('requires real connected cable; a solved switch array alone cannot open it',()=>{const {g,tag}=fixture('city_2');for(let i=0;i<6;i++)tag(`switch-${i+1}`).switchOn=[false,true,true,false,true,true][i];const cable=g.world.entities.find(e=>e.type==='cable'&&e.x===(40+10)*64+32&&e.y===(30+9)*64+32)!;g.destroy(cable);settle(g);expect(tag('computer-door').open).toBe(false);});
 it('has exactly one sustained five-switch solution and a distinct five-second trap',()=>{for(let bits=0;bits<32;bits++){const {g,tag}=fixture('city_7');for(let i=0;i<5;i++)tag(`switch-${i+1}`).switchOn=!!(bits&(1<<i));settle(g,2);expect(tag('trap-door').open,`initial ${bits}`).toBe(bits===25||bits===17);settle(g,5);expect(tag('trap-door').open,`sustained ${bits}`).toBe(bits===25);}});
 it('requires all three weighted platforms for the inner vault',()=>{const {g,tag}=fixture('city_7');for(let i=1;i<=3;i++){g.drop(stack(g.world,'stone'),tag(`platform-${i}`));settle(g);expect(tag('vault-door').open).toBe(i===3);}});
});
