import 'fake-indexeddb/auto';
import {IDBObjectStore} from 'fake-indexeddb';
import {describe,it,expect,vi} from 'vitest';
import {blankWorld} from '../src/world/generate';
import {SaveStore,checksum,decode,envelope} from '../src/persistence/saves';

describe('save slots and recovery',()=>{
 it('keeps the immediately preceding generation when independent windows save concurrently',async()=>{const name='concurrent-'+crypto.randomUUID(),a=new SaveStore(name),b=new SaveStore(name),w=blankWorld();await a.save('manual-1',w,'Original');const first=structuredClone(w),second=structuredClone(w);first.player.hp=201;second.player.hp=102;const writes=await Promise.all([a.save('manual-1',first,' Window A '),b.save('manual-1',second,'Window B')]);const latest=(await a.list())[0];const preceding=writes.find(s=>s.current.snapshot!==latest.current.snapshot)!;expect(latest.previous?.snapshot).toBe(preceding.current.snapshot);expect([201,102]).toContain((await decode(latest.previous)).player.hp);expect(writes[0].name).toBe('Window A');await a.close();await b.close();});
 it('lists deleted slots separately and refuses to restore over an occupied slot',async()=>{const s=new SaveStore('trash-'+crypto.randomUUID()),w=blankWorld();await s.save('manual-3',w,'Recover me');await s.trash('manual-3');expect((await s.list(true)).map(s=>s.key)).toEqual(['trash-manual-3']);await s.save('manual-3',w,'Keep me');await expect(s.restore('manual-3')).rejects.toThrow('occupied');expect((await s.load('manual-3')).slot.name).toBe('Keep me');expect(await s.list(true)).toHaveLength(2);await s.close();});
 it('recovers the previous valid generation from an actually corrupted stored slot',async()=>{const name='corrupt-'+crypto.randomUUID(),s=new SaveStore(name),w=blankWorld();await s.save('manual-1',w,'First');w.player.hp=99;await s.save('manual-1',w,'Second');const slot=(await s.list())[0];slot.current.checksum='damaged';const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(name);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});await new Promise<void>((resolve,reject)=>{const t=db.transaction('slots','readwrite');t.objectStore('slots').put(slot);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);});const recovered=await s.load('manual-1');expect(recovered.recovered).toBe(true);expect(recovered.world.player.hp).toBe(255);db.close();await s.close();});
 it('keeps twelve independent manual slots and three separate autosaves',async()=>{const s=new SaveStore('slots-'+crypto.randomUUID());for(let i=1;i<=12;i++){const w=blankWorld(`seed${i}`,`World ${i}`);await s.save(`manual-${i}`,w,w.name);}for(let i=0;i<3;i++)await s.save(`auto-${i}`,blankWorld('auto'),'Auto');expect(await s.list()).toHaveLength(15);for(let i=1;i<=12;i++)expect((await s.load(`manual-${i}`)).world.seed).toBe(`seed${i}`);await s.close();});
 it('retains a previous generation and keeps it through an interrupted transaction',async()=>{const name='atomic-'+crypto.randomUUID(),s=new SaveStore(name),w=blankWorld();await s.save('manual-1',w,'First');w.player.hp=123;await s.save('manual-1',w,'Second');const slot=(await s.list())[0];expect((await decode(slot.previous)).player.hp).toBe(255);const broken=new SaveStore(name,'abort');w.player.hp=22;await expect(broken.save('manual-1',w,'Interrupted')).rejects.toThrow();expect((await s.load('manual-1')).world.player.hp).toBe(123);await broken.close();await s.close();});
 it('preserves the current slot on quota failure, rejects corruption and future imports',async()=>{const s=new SaveStore('quota-'+crypto.randomUUID()),w=blankWorld();await s.save('manual-1',w,'Good');const spy=vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(()=>{throw new DOMException('Quota reached','QuotaExceededError');});await expect(s.save('manual-1',w,'Bad')).rejects.toThrow('Quota');spy.mockRestore();expect((await s.load('manual-1')).slot.name).toBe('Good');const e=await envelope(w);await expect(s.import(JSON.stringify({...e,checksum:'broken'}),'manual-1')).rejects.toThrow('checksum');await expect(s.import(JSON.stringify({...e,schema:99}),'manual-1')).rejects.toThrow('newer');expect((await s.load('manual-1')).slot.name).toBe('Good');await s.close();});
 it('rejects bad counts and unknown items even with a matching checksum',async()=>{const w=blankWorld(),e=await envelope(w),bad=JSON.parse(e.payload);bad.player.inventory[0]={uid:'hack',item:'unknown',quantity:10,freshness:-1,loaded:0};const payload=JSON.stringify(bad);await expect(decode({...e,payload,checksum:await checksum(payload)})).rejects.toThrow('identity');});
 it('supports a known schema migration and recoverable slot deletion',async()=>{const s=new SaveStore('migration-'+crypto.randomUUID()),w=blankWorld(),e=await envelope(w),legacy=JSON.parse(e.payload);legacy.schema=1;delete legacy.contentVersion;delete legacy.autosaveClock;delete legacy.player.milestones;const payload=JSON.stringify(legacy);await s.import(JSON.stringify({...e,schema:1,payload,checksum:await checksum(payload)}),'manual-2','Migrated');expect((await s.load('manual-2')).world.schema).toBe(2);await s.trash('manual-2');expect(await s.list()).toHaveLength(0);await s.restore('manual-2');expect((await s.load('manual-2')).slot.name).toBe('Migrated');await s.close();});
});
