import {describe,it,expect} from 'vitest';
import {BALANCE,DATA,ITEMS,RECIPES} from '../src/content';
import {Game} from '../src/core/game';
import {add,count,moveSlot,stack,transfer} from '../src/core/inventory';
import {blankWorld,generateWorld} from '../src/world/generate';
import {canonical,decode,envelope,validateWorld} from '../src/persistence/saves';
import {attack,updateCombat} from '../src/systems/combat';
import {updateCircuits,gateValue} from '../src/systems/circuits';
import {updateProduction} from '../src/systems/production';
import {updateSurvival,updateAction} from '../src/systems/survival';
import {updateActors} from '../src/systems/ai';

const idle={x:0,y:0,sprint:false,aim:0,attack:false};
const fixture=()=>new Game(blankWorld('test','Test world'));
const give=(g:Game,id:string,n:number,loaded=0)=>add(g.player.inventory,stack(g.world,id,n,loaded));
const run=(g:Game,seconds:number)=>{for(let i=0;i<Math.round(seconds*60);i++)g.step(idle);};

describe('content and the opening',()=>{
 it('has reachable production chains including Tesla fuel bootstrap and uranium construction',()=>{
  const reachable=new Set(['wood','stone','iron','sulfur','uranium','orange','tomato','raw_steak','leather','animal_tendon','animal_fat','junk','can','electronic_parts','energy_cells','big_wires','small_wire','chemical_component','syringe','ghoul_blood','boletus','russula','amanita','rare_flower','acorn']);
  const stations=new Set(['hand']);let changes=true;while(changes){changes=false;for(const r of Object.values(RECIPES)){expect(r.ingredients.every(i=>ITEMS[i.item_id]&&Number.isInteger(i.quantity)&&i.quantity>0)).toBe(true);if(stations.has(r.station)&&r.ingredients.every(i=>reachable.has(i.item_id))){if(!reachable.has(r.id)){reachable.add(r.id);changes=true;}if(!stations.has(r.id)){stations.add(r.id);changes=true;}}}}
  expect(Object.keys(RECIPES).filter(id=>!reachable.has(id))).toEqual([]);expect(reachable.has('tesla_armor')&&reachable.has('uranium_door')).toBe(true);
 });
 it('generates a complete serializable world with only two starting stones',()=>{const w=generateWorld('28629483','Fresh');expect(()=>validateWorld(w)).not.toThrow();expect(w.player.inventory.filter(Boolean)).toHaveLength(1);expect(count(w.player.inventory,'stone')).toBe(2);expect(w.regions.filter(r=>r.id.startsWith('city_'))).toHaveLength(9);expect(w.entities.filter(e=>e.type==='rare_flower')).toHaveLength(1);});
 it('makes the first hatchet by harvesting with fists and consuming the initial stones',()=>{const g=fixture();give(g,'stone',2);const e=g.create('tree',g.player.x+75,g.player.y);while(count(g.player.inventory,'wood')<10)g.harvest(e,'fists');const wood=count(g.player.inventory,'wood');expect(g.craft('hatchet')).toBe(true);expect(count(g.player.inventory,'stone')).toBe(0);run(g,3);expect(count(g.player.inventory,'hatchet')).toBe(1);expect(count(g.player.inventory,'wood')).toBe(wood-10);});
});
describe('inventory, consumption and industry',()=>{
 it('preserves old freshness through partial transfers and splits',()=>{const g=fixture(),a=stack(g.world,'orange',18),b=stack(g.world,'orange',19);a.freshness=500;b.freshness=15;const from=[a,null],to=[b,null];expect(transfer(from,0,to,10)).toBe(10);expect(to[0]?.quantity).toBe(20);expect(to[0]?.freshness).toBe(15);expect(from[0]?.quantity).toBe(8);expect(to[1]?.quantity).toBe(9);moveSlot(from,0,1,true);expect(from[0]?.quantity).toBe(4);expect(from[1]?.freshness).toBe(500);});
 it('returns a soup can once, including when consumption is restored mid-action',async()=>{const g=fixture();give(g,'tomato_soup',1);g.player.selected=0;g.player.hunger=20;g.useSelected();updateAction(g,.6);const loaded=new Game(await decode(await envelope(g.world)));updateAction(loaded,1.5);updateAction(loaded,10);expect(count(loaded.player.inventory,'tomato_soup')).toBe(0);expect(count(loaded.player.inventory,'can')).toBe(1);expect(loaded.player.hunger).toBe(180);});
 it('reserves four sequential jobs once, pauses on empty fuel, and resumes after load',async()=>{const g=fixture();give(g,'iron',8);const e=g.create('firepit',g.player.x+80,g.player.y,g.player.owner);e.fuel=1;for(let i=0;i<4;i++)expect(g.craft('shaped_metal',e)).toBe(true);expect(count(g.player.inventory,'iron')).toBe(0);expect(g.craft('shaped_metal',e)).toBe(false);for(let i=0;i<2000;i++)updateProduction(g,.02);expect(count(e.outputs,'shaped_metal')).toBe(1);const remaining=e.jobs[0].remaining;updateProduction(g,5);expect(e.jobs[0].remaining).toBe(remaining);const loaded=new Game(await decode(await envelope(g.world))),le=loaded.byId.get(e.id)!;le.fuel=5;for(let i=0;i<2000;i++)updateProduction(loaded,.02);expect(count(le.outputs,'shaped_metal')).toBe(4);expect(le.jobs).toHaveLength(0);});
 it('releases completed outputs, queued inputs, stored items, and unburned fuel exactly once on destruction',()=>{const g=fixture(),e=g.create('firepit',g.player.x+80,g.player.y,g.player.owner);give(g,'iron',4);g.craft('shaped_metal',e);add(e.inventory,stack(g.world,'wood',8));add(e.outputs,stack(g.world,'shaped_metal',2));e.fuel=5;g.destroy(e);g.destroy(e);const drops=g.world.entities.filter(x=>x.active&&x.kind==='drop').flatMap(x=>x.inventory);expect(count(drops,'iron')).toBe(2);expect(count(drops,'wood')).toBe(13);expect(count(drops,'shaped_metal')).toBe(2);});
 it('Builder doubles construction batches and leaves ammunition unchanged',()=>{const g=fixture();g.player.inventory=Array(14).fill(null);g.player.upgrades.push('builder_1');give(g,'wood',100);const e=g.create('workbench',g.player.x+80,g.player.y,g.player.owner);g.player.unlocked.push('wooden_arrow');expect(g.craft('wood_floor',e)).toBe(true);expect(e.jobs[0].output).toBe(RECIPES.wood_floor.output_quantity*2);expect(g.craft('wooden_arrow',e)).toBe(true);expect(e.jobs[1].output).toBe(RECIPES.wooden_arrow.output_quantity);});
});
describe('survival and combat interactions',()=>{
 it('cannot regenerate through starvation and cold, and daylight restores zero warmth',()=>{const g=fixture();g.world.time=500;g.player.hp=100;g.player.hunger=0;g.player.warmth=0;g.player.lastDamage=-100;updateSurvival(g,1);expect(g.player.hp).toBe(93);g.world.time=100;g.player.hunger=200;updateSurvival(g,1);expect(g.player.warmth).toBeGreaterThan(0);expect(g.player.hp).toBe(93);});
 it('does not confuse lamp light with warmth or stack ghoul lamp damage',()=>{const g=fixture();g.world.time=500;g.player.warmth=100;const a=g.create('lamp',g.player.x+64,g.player.y);a.signal=true;const b=g.create('lamp',g.player.x+64,g.player.y+64);b.signal=true;const ghoul=g.create('normal_ghoul',g.player.x+130,g.player.y);updateSurvival(g,1);updateActors(g,1);expect(g.player.warmth).toBe(96.5);expect(ghoul.hp).toBe(159);});
 it('uses one shell for five pellets; full walls block all pellets while low walls allow them',()=>{const close=fixture();give(close,'shotgun',1,1);close.player.selected=0;const near=close.create('armored_ghoul',close.player.x+100,close.player.y);attack(close);expect(close.world.projectiles).toHaveLength(5);expect(close.selected()?.loaded).toBe(0);updateCombat(close,.2);expect(near.hp).toBe(695);
  for(const low of [false,true]){const g=fixture();give(g,'shotgun',1,1);g.player.selected=0;g.create(low?'wood_low_wall':'wood_wall',g.player.x+70,g.player.y);const enemy=g.create('armored_ghoul',g.player.x+170,g.player.y);attack(g);updateCombat(g,.25);expect(enemy.hp).toBe(low?737:800);}});
 it('saves actual loaded rounds independently from reserve ammunition during reload',async()=>{const g=fixture();give(g,'9mm',1,3);give(g,'bullet',30);g.player.selected=0;expect(g.reload()).toBe(true);expect(count(g.player.inventory,'bullet')).toBe(13);const loaded=new Game(await decode(await envelope(g.world)));updateAction(loaded,3);expect(loaded.selected()?.loaded).toBe(20);expect(count(loaded.player.inventory,'bullet')).toBe(13);});
 it('separates ghoul spawn presence from automatic age hostility',()=>{const g=fixture();g.world.time=500;const e=g.create('normal_ghoul',g.player.x+160,g.player.y);g.player.age=900;updateActors(g,.1);expect(e.ai?.target).toBeNull();g.player.age=961;updateActors(g,.1);expect(e.ai?.target).toBe('player');});
});
describe('circuits in the spatial world',()=>{
 it('evaluates all physical three-input combinations including exactly-one XOR',()=>{for(const type of ['gate_or','gate_and','gate_xor'])for(let bits=0;bits<8;bits++){
  const g=fixture(),x=1056,y=4128,gate=g.create(type,x,y);const inputs=[!!(bits&1),!!(bits&2),!!(bits&4)];for(const [i,dx,dy]of [[0,0,-64],[1,0,64],[2,-64,0]]){const s=g.create('switch',x+dx,y+dy);s.switchOn=inputs[i];}const lamp=g.create('lamp',x+64,y);updateCircuits(g,.1);updateCircuits(g,.1);const n=inputs.filter(Boolean).length;expect(lamp.signal).toBe(type==='gate_or'?n>0:type==='gate_and'?n===3:n===1);
 }});
 it('keeps cable bridge channels separate and supports weighted platforms',()=>{const g=fixture(),x=1056,y=4128;g.player.x=500;g.player.y=500;g.create('cable_bridge',x,y);const north=g.create('switch',x,y-64);north.switchOn=true;g.create('switch',x-64,y);const east=g.create('lamp',x+64,y),south=g.create('lamp',x,y+64);updateCircuits(g,.1);expect(south.signal).toBe(true);expect(east.signal).toBe(false);const platform=g.create('platform',x+300,y);const lamp=g.create('lamp',x+364,y);g.drop(stack(g.world,'stone',1),platform);updateCircuits(g,.1);expect(lamp.signal).toBe(true);});
 it('fans NOT to three outputs and bounds a feedback circuit without recursion',()=>{const g=fixture(),x=1056,y=4128;const gate=g.create('gate_not',x,y),lamps=[g.create('lamp',x,y-64),g.create('lamp',x+64,y),g.create('lamp',x,y+64)];updateCircuits(g,.1);updateCircuits(g,.1);expect(lamps.every(l=>l.signal)).toBe(true);g.create('cable',x-64,y);for(let i=0;i<100;i++)updateCircuits(g,.1);expect(typeof gate.signal).toBe('boolean');});
});
describe('durable deterministic simulation',()=>{
 it('round trips a complex fixture and continues identically across every system',async()=>{const g=fixture();g.player.inventory=Array(14).fill(null);give(g,'9mm',1,7);give(g,'raw_steak',4);give(g,'iron',8);g.player.selected=0;g.player.effects.withdrawal=200;g.player.radiation=80;g.player.age=1000;g.world.time=490;
  const station=g.create('firepit',g.player.x+100,g.player.y,g.player.owner);station.fuel=8;g.craft('shaped_metal',station);const tree=g.create('tree_seed',g.player.x-160,g.player.y,g.player.owner);tree.growAt=g.world.time+130;const ore=g.create('iron_node',g.player.x+450,g.player.y);ore.yieldLeft=30;ore.hp=90;
  const wall=g.create('wood_wall',g.player.x-250,g.player.y,g.player.owner);wall.hp=1000;g.create('lapabot',g.player.x-400,g.player.y,g.player.owner);g.create('normal_ghoul',g.player.x+350,g.player.y);g.create('dynamite',g.player.x+900,g.player.y,g.player.owner);const timer=g.create('gate_timer',g.player.x,g.player.y+128);timer.timerPhase=3.5;g.create('lamp',g.player.x+64,g.player.y+128);
  run(g,1);const restored=new Game(await decode(await envelope(g.world)));expect(canonical(restored.world)).toBe(canonical(g.world));run(g,7);run(restored,7);expect(canonical(restored.world)).toBe(canonical(g.world));
 });
 it('freezes every saved field during pause and does not use wall time after loading',async()=>{const g=fixture();const before=canonical(g.world);g.paused=true;run(g,20);expect(canonical(g.world)).toBe(before);const e=await envelope(g.world);e.savedAt-=86400000;const loaded=await decode(e);expect(canonical(loaded)).toBe(before);});
 it('replays the same fixed ticks under 30, 60, and 144 Hz render schedules',()=>{const original=fixture().world;const results=[];for(const hz of [30,60,144]){const g=new Game(structuredClone(original));let accumulator=0;for(let frame=0;frame<hz*2;frame++){accumulator+=1/hz;while(accumulator>=BALANCE.step-1e-12){g.step({...idle,x:1});accumulator-=BALANCE.step;}}results.push(canonical(g.world));}expect(results[0]).toBe(results[1]);expect(results[1]).toBe(results[2]);});
});
